name: "build-test"
on: [pull_request]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6 # v2.6.0

    - name: docker build
      run: docker build . -t container-structure-test:dev

    - name: run action
      uses: ./
      with:
        image: container-structure-test:dev
        config: test/test.yaml
